# Generated by Django 5.0.6 on 2024-06-04 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_pacjenci'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='terminy',
            name='data',
            field=models.DateField(blank=True, default='2023-01-01'),
        ),
        migrations.AddField(
            model_name='terminy',
            name='godzina',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='terminy',
            name='lekarz',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='terminy_lekarz', to='api.lekarze'),
        ),
        migrations.AddField(
            model_name='terminy',
            name='pacjent',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='terminy_pacjent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='terminy',
            name='placowka',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='terminy_placowka', to='api.placowki'),
        ),
        migrations.AddField(
            model_name='terminy',
            name='szczegoly',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='terminy',
            name='wiadomosc_dla_lekarza',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
