# Generated by Django 5.0.6 on 2024-06-04 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_terminy_data_terminy_godzina_terminy_lekarz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminy',
            name='godzina',
            field=models.TimeField(blank=True, default='18:30'),
        ),
    ]
