# Generated by Django 5.0.6 on 2024-06-04 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_terminy_pacjent'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminy',
            name='miasto',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
